sonar.projectKey=Mahery23_skillhub-examen
sonar.organization=mahery23

# Sources : Laravel + React + Spring Boot
sonar.sources=backend/app,frontend/src,auth-service/src/main
sonar.tests=backend/tests,frontend/src,auth-service/src/test
sonar.test.inclusions=frontend/src/**/*.test.js,frontend/src/**/*.test.jsx

# Rapports de coverage
sonar.php.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.coverage.jacoco.xmlReportPaths=auth-service/target/site/jacoco/jacoco.xml

# Exclusions
sonar.exclusions=**/vendor/**,**/node_modules/**,**/dist/**,**/target/**,**/storage/**,**/bootstrap/cache/**,**/*.blade.php,**/public/**,**/coverage/**

sonar.coverage.exclusions=backend/app/Console/**,backend/app/Exceptions/**,backend/app/Providers/**,backend/database/**,frontend/src/main.jsx,frontend/src/App.jsx,frontend/src/pages/**,frontend/vite.config.js,auth-service/src/main/java/com/example/authserver/AuthserverApplication.java

sonar.sourceEncoding=UTF-8