name: CI/CD — SkillHub

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:

  # ─────────────────────────────────────────
  # JOB 1 — Spring Boot : build + test + sonar
  # ─────────────────────────────────────────
  auth-service:
    name: Auth Service — Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Install + Test + Coverage JaCoCo
      - name: Install, Test, Coverage
        working-directory: auth-service
        env:
          APP_MASTER_KEY: test_master_key_for_ci_only_32chars
        run: mvn verify -B

      # Sonar Spring Boot
      - name: SonarCloud — Auth Service
        working-directory: auth-service
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          APP_MASTER_KEY: test_master_key_for_ci_only_32chars
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=Mahery23_skillhub-examen \
            -Dsonar.organization=mahery23 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} -B


  # ─────────────────────────────────────────
  # JOB 2 — Laravel + React : lint + test + sonar
  # ─────────────────────────────────────────
  ci:
    name: Laravel + React — Lint · Test · Sonar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ── PHP Setup ──
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo, pdo_mysql, zip, bcmath, gd, mongodb-2.2.0
          coverage: pcov

      # Install Laravel
      - name: Install — Composer
        working-directory: ./backend
        run: |
          mkdir -p bootstrap/cache storage/logs \
                   storage/framework/{cache,sessions,views}
          composer install --no-interaction --optimize-autoloader \
                           --ignore-platform-req=ext-mongodb

      # Lint Laravel
      - name: Lint — PHP CS
        working-directory: ./backend
        run: ./vendor/bin/phpcs --standard=PSR12 app/ || true

      # Tests Laravel (inclut test limite 5 inscriptions — Q1)
      - name: Test — Laravel
        working-directory: ./backend
        env:
          APP_ENV: testing
          APP_KEY: base64:dGVzdGluZ19rZXlfMzJfYnl0ZXNfZm9yX3BocHVuaXRfMjAyNg==
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
          DB_FOREIGN_KEYS: "false"
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          AUTH_SERVICE_URL: http://localhost:8080
        run: php artisan test --coverage-clover=coverage.xml

      # ── Node Setup ──
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      # Install + Lint + Test React
      - name: Install — npm
        working-directory: ./frontend
        run: npm ci

      - name: Lint — ESLint
        working-directory: ./frontend
        run: npm run lint || true

      - name: Test — React
        working-directory: ./frontend
        run: npm run test:coverage

      # Sonar Laravel + React
      - name: SonarCloud — Laravel + React
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  # ─────────────────────────────────────────
  # JOB 3 — Build + Push images Docker
  # Push uniquement sur merge → main
  # ─────────────────────────────────────────
  docker:
    name: Docker — Build & Push
    runs-on: ubuntu-latest
    needs: [auth-service, ci]
    steps:
      - uses: actions/checkout@v4

      # Build des 3 images taguées avec le SHA du commit
      - name: Build images
        run: |
          docker build -t skillhub-api:${{ github.sha }} ./backend
          docker build -t skillhub-auth:${{ github.sha }} ./auth-service
          docker build \
            --build-arg VITE_API_BASE_URL=http://localhost:8000 \
            -t skillhub-frontend:${{ github.sha }} ./frontend

      # Push vers registry — uniquement sur main
      - name: Login registry
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Push — Auth Service
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          context: ./auth-service
          push: true
          tags: |
            ${{ secrets.REGISTRY_USER }}/skillhub-auth:${{ github.sha }}
            ${{ secrets.REGISTRY_USER }}/skillhub-auth:latest

      - name: Push — Laravel API
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.REGISTRY_USER }}/skillhub-api:${{ github.sha }}
            ${{ secrets.REGISTRY_USER }}/skillhub-api:latest

      - name: Push — Frontend
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          build-args: VITE_API_BASE_URL=http://localhost:8000
          tags: |
            ${{ secrets.REGISTRY_USER }}/skillhub-frontend:${{ github.sha }}
            ${{ secrets.REGISTRY_USER }}/skillhub-frontend:latest